### ISSUE TITLE
FiftyOne.Pipeline.Core.Exceptions.PipelineException in CombiningService example.

### ISSUE THREAD

**Issue by tungntpham** [51Degrees/location-dotnet#1]
location-dotnet CombiningServices example is throwing the following exception. This is observed in the location-dotnet-test pipeline:

```
FiftyOne.Pipeline.Core.Exceptions.PipelineException: Unable to determine the type associated with this property. No c# property found matching definition DeviceDataCloud.SupportedI/O and json type 'Array' is not mapped.
```

The cause looks be the '/' included in the definition for `DeviceDataCloud.SupportedI/O` which is not allowed in the corresponding property name. Thus, no match can be found for `DeviceDataCloud.SupportedI/O` and resulsted in an exception.

**Comment by Steve51D** [comment]
Although this issue is present in this example in location-dotnet, the root cause is elsewhere.
Please see [this issue](https://github.com/51Degrees/device-detection-dotnet/issues/18) for updates.
