### ISSUE TITLE
Build Error when compile in Visual Studio.

### ISSUE THREAD

**Issue by tungntpham** [51Degrees/location-dotnet#2]
Get the following error, when build with Visual Studio:
```
error : The value of SourceRoot.RepositoryUrl with identity 'E:\work\location-dotnet\' is invalid: 'https://github.com/51Degrees/location-dotnet.git'
```

Looks to be related to [this](https://github.com/dotnet/sourcelink/issues/410).

**Comment by Steve51D** [comment]
This has been resolved by removing the source link dependencies from these projects.
